spring:
  datasource:
    url: jdbc:mysql://192.168.2.251:3206/db_item?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true
  jwt:
    secret: mySecretProviderAdminsecldfld9sfd434fsdfsdff7sdf9sd0f12lfSDFdfdFWEflS3434ADSADdfdsfDSAD132456erwerwe
    expiration: 604800