spring:
  datasource:
    url: jdbc:mysql://192.168.2.251:3306/db_archive?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true