test:
  name: zhagnsa423445455
  age: 19
  add: 成都
eureka:
  client:
    service-url:
      defualtZone: http://localhost:1111/eureka/
server:
  port: 2222
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest  