spring:
  datasource:
    url: jdbc:mysql://192.168.2.251:3306/db_express?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true
  express:
    monthCode: "0286773560"
    #1 运单号  2 订单号
    expressNoType: 1
    #1 顺丰标快 2 顺丰特惠
    expressType: 2
    clientCode: SCZQKHYLKJ
    sfRequestUrl: https://bsp-oisp.sf-express.com/bsp-oisp/sfexpressService
    sfPassword: Epw5T58m79qhUkT7SSh8tkfwE3aSwzZ3