spring:
  datasource:
    url: jdbc:mysql://192.168.40.128:3206/db_healthy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true