spring:
  datasource:
    url: jdbc:mysql://192.168.2.251:3206/db_im?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true
  jwt:
    secret: mySecretProvider
    expiration: 604800
  sitemap:
    url: http://192.168.2.251/app-h5/v1.0/sitemap.json
oss:
  url: http://file-devel.oss-cn-beijing.aliyuncs.com