spring:
  datasource:
    url: jdbc:mysql://192.168.2.251:3206/db_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true