spring:
  supperVip:
    userId: sadksadldsadss1213456
  datasource:
    url: jdbc:mysql://192.168.2.251:3206/db_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true