spring:
  datasource:
    url: jdbc:mysql://192.168.2.251:3206/wallet?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true
  fee:
    companyPercent: 0.01
    bankPercent: 0.01
    withdrawPercent: 0.015
  account:
    accountId: 999999999
  user:
    userId: 999999999